settings:
  name: "Product Name"
  release_notes: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  

sidebar: 
  entries:
  - title: Legal notices
    url: /legal-notices.html
